### ISSUE TITLE
Rendre compatible un addons avec celui la

### ISSUE THREAD

**Issue by RKalash62** [MaaxIT/voice_system#2]
Bonjour, pouvez vous rendre compatible votre addon avec celui-ci: https://steamcommunity.com/sharedfiles/filedetails/?id=737856583
merci

**Comment by MaaxIT** [comment]
Bonjour,

Cette page GitHub a été créé dans l'objectif que les créateurs de l'addon puissent rendre compatible le leur avec le Voice System facilement.
Malheureusement, l'addon que vous m'avez envoyé utilise une façon de code que je n'arrive pas à comprendre et je n'aimerai pas casser le mien à cause de ça.

Je vous invite donc à aller contacter le créateur de l'addon en question et de lui envoyer la page GitHub en lien pour qu'il puisse, par lui-même, ajouter sa compatibilité au fichier.
Il comprendra mieux que moi comment son système fonctionne et comment facilement l'intégrer avec le mien.

Merci.
